### ISSUE TITLE
HCaptcha support

### ISSUE THREAD

**Issue by posix4e** [BigDataBoutique/ElastiQuill#23]
Hi I'm a cofounder of HCaptcha. I'd like to add HCaptcha support to block bots, but site owners could use it as an easy way of monetizing as well. What do you think?

**Comment by synhershko** [comment]
Sure, feel free to submit a PR

**Comment by catgirlsec** [comment]
Is there going to be some sort of Abstract captcha class if you’re supporting several captcha providers? Now would be a really good time to implement it to reduce technical debt later on.

**Comment by catgirlsec** [comment]
Some general feedback I checked the website https://www.hcaptcha.com/ on my iPhone and the bounding box captcha was hellish to complete.

**Comment by synhershko** [comment]
Closing for lack of interest
